/** Player-facing copy (Maggy, 25-sep-2026). Default versions omit on-chain wording. */
export const COPY = {
  title: 'ChainLords Kill Ledger',
  subtitle: "Every enemy kill, sealed by the realm's server.",
  subtitleOnchain: "Every enemy kill, sealed by the realm's server and inscribed on-chain.",
  footer: "Kills are recorded by the realm's server. The same two heroes count at most 2 kills a day and 10 a week.",
  footerOnchain: "Kills are recorded by the realm's server and sealed on-chain. The same two heroes count at most 2 kills a day and 10 a week.",
  delayLine: (delay: string) => `Kills appear ${delay} after they happen. Times are rounded.`,
  lootDelayLine: (delay: string) => `Loot is revealed ${delay} after the kill.`,
  search: 'Search a hero…',
  sampleBanner: 'SAMPLE / MOCK DATA — fictional characters for local preview. Not real ChainLords data.',
  statuses: {
    credited: { label: 'Counted', hint: 'This kill counts.' },
    pair_limit_reached: { label: 'Limit reached', hint: "These two heroes fought too often. This kill doesn't count." },
    kill_burned: { label: 'Voided', hint: "The realm voided this kill. It doesn't count." },
    rejected_level_gap: { label: 'Level gap', hint: "The level difference was too wide. This kill doesn't count." },
  },
  unranked: 'Unranked · last 30 days',
  rank: (n: number) => `Rank #${n} · last 30 days`,
  statKills: 'Kills',
  statKillScore: 'Kill score',
  statDeaths: 'Deaths',
  statZemLooted: 'Zem looted',
  statTop10: 'Top 10 slain',
  statTop30: 'Top 30 slain',
  noKillsYet: 'No kills yet.',
  neverFallen: 'Never fallen.',
  noLoot: 'No loot',
  bound: 'Bound',
  rankingsTitle: 'City rankings · Top 30',
  rankingsWindow: 'Last 30 days',
  colKills: 'Kills',
  colKillScore: 'Kill score',
  colWorth: 'Worth if slain',
  explainer: 'Slay a Top 10 hero of the rival city and the kill counts ×3. Top 30 counts ×2. Everyone else counts ×1. Ranks come from kills in the last 30 days, and a hero\'s rank is locked the moment they fall.',
} as const;
