/**
 * Maps Helbreath Olympia magic IDs (Magic.cfg) to multiplayer server spell catalog ids.
 * Spells without an entry are handled client-side only (VFX / utility).
 */
import {
    SPELL_ARMOR_BREAK_ID,
    SPELL_BERSERK_ID,
    SPELL_BLOODY_SHOCK_WAVE_ID,
    SPELL_BLIZZARD_ID,
    SPELL_CHILL_WIND_ID,
    SPELL_EARTH_SHOCK_WAVE_ID,
    SPELL_EARTHWORM_STRIKE_ID,
    SPELL_ENERGY_BOLT_ID,
    SPELL_ENERGY_STRIKE_ID,
    SPELL_FIRE_BALL_ID,
    SPELL_FIRE_FIELD_ID,
    SPELL_FIRE_STRIKE_ID,
    SPELL_ICE_STORM_ID,
    SPELL_ICE_STRIKE_ID,
    SPELL_INVISIBILITY_ID,
    SPELL_LIGHTNING_BOLT_ID,
    SPELL_LIGHTNING_STRIKE_ID,
    SPELL_MASS_BLIZZARD_ID,
    SPELL_MASS_CHILL_WIND_ID,
    SPELL_MASS_FIRE_STRIKE_ID,
    SPELL_MASS_ICE_STRIKE_ID,
    SPELL_MASS_LIGHTNING_ARROW_ID,
    SPELL_METEOR_STRIKE_ID,
    SPELL_POISON_CLOUD_ID,
    SPELL_SPIKE_FIELD_ID,
    SPELL_TRIPLE_ENERGY_BOLT_ID,
} from './Spells';

/** Server Spells.json id constants (mp multiplayer catalog). */
const SERVER = {
    ENERGY_BOLT: 0,
    FIRE_BALL: 1,
    FIRE_STRIKE: 2,
    CHILL_WIND: 3,
    POISON_CLOUD: 4,
    TRIPLE_ENERGY_BOLT: 5,
    LIGHTNING_BOLT: 6,
    SPIKE_FIELD: 7,
    FIRE_FIELD: 8,
    ICE_STORM: 9,
    ICE_STRIKE: 10,
    ENERGY_STRIKE: 11,
    MASS_FIRE_STRIKE: 12,
    MASS_CHILL_WIND: 13,
    EARTHWORM_STRIKE: 14,
    ARMOR_BREAK: 15,
    BLOODY_SHOCK_WAVE: 16,
    MASS_ICE_STRIKE: 17,
    LIGHTNING_STRIKE: 18,
    METEOR_STRIKE: 19,
    MASS_LIGHTNING_STRIKE: 20,
    BLIZZARD: 21,
    EARTH_SHOCK_WAVE: 22,
    MASS_BLIZZARD: 23,
    INVISIBILITY: 24,
    BERSERK: 25,
} as const;

const OLYMPIA_TO_SERVER: Readonly<Record<number, number>> = {
    [SPELL_ENERGY_BOLT_ID]: SERVER.ENERGY_BOLT,
    [SPELL_FIRE_BALL_ID]: SERVER.FIRE_BALL,
    [SPELL_FIRE_STRIKE_ID]: SERVER.FIRE_STRIKE,
    [SPELL_CHILL_WIND_ID]: SERVER.CHILL_WIND,
    [SPELL_POISON_CLOUD_ID]: SERVER.POISON_CLOUD,
    [SPELL_TRIPLE_ENERGY_BOLT_ID]: SERVER.TRIPLE_ENERGY_BOLT,
    [SPELL_LIGHTNING_BOLT_ID]: SERVER.LIGHTNING_BOLT,
    [SPELL_SPIKE_FIELD_ID]: SERVER.SPIKE_FIELD,
    [SPELL_FIRE_FIELD_ID]: SERVER.FIRE_FIELD,
    [SPELL_ICE_STORM_ID]: SERVER.ICE_STORM,
    [SPELL_ICE_STRIKE_ID]: SERVER.ICE_STRIKE,
    [SPELL_ENERGY_STRIKE_ID]: SERVER.ENERGY_STRIKE,
    [SPELL_MASS_FIRE_STRIKE_ID]: SERVER.MASS_FIRE_STRIKE,
    [SPELL_MASS_CHILL_WIND_ID]: SERVER.MASS_CHILL_WIND,
    [SPELL_EARTHWORM_STRIKE_ID]: SERVER.EARTHWORM_STRIKE,
    [SPELL_ARMOR_BREAK_ID]: SERVER.ARMOR_BREAK,
    [SPELL_BLOODY_SHOCK_WAVE_ID]: SERVER.BLOODY_SHOCK_WAVE,
    [SPELL_MASS_ICE_STRIKE_ID]: SERVER.MASS_ICE_STRIKE,
    [SPELL_LIGHTNING_STRIKE_ID]: SERVER.LIGHTNING_STRIKE,
    [SPELL_METEOR_STRIKE_ID]: SERVER.METEOR_STRIKE,
    [SPELL_MASS_LIGHTNING_ARROW_ID]: SERVER.MASS_LIGHTNING_STRIKE,
    [SPELL_BLIZZARD_ID]: SERVER.BLIZZARD,
    [SPELL_EARTH_SHOCK_WAVE_ID]: SERVER.EARTH_SHOCK_WAVE,
    [SPELL_MASS_BLIZZARD_ID]: SERVER.MASS_BLIZZARD,
    [SPELL_INVISIBILITY_ID]: SERVER.INVISIBILITY,
    [SPELL_BERSERK_ID]: SERVER.BERSERK,
};

export function getOlympiaServerSpellId(olympiaSpellId: number): number | undefined {
    return OLYMPIA_TO_SERVER[olympiaSpellId];
}

export function isServerAuthoritativeOlympiaSpell(olympiaSpellId: number): boolean {
    return OLYMPIA_TO_SERVER[olympiaSpellId] !== undefined;
}